# Generated by Django 4.1.3 on 2022-11-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_parkingspot_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='res',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reservation'),
        ),
    ]
