# Generated by Django 4.1.3 on 2022-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_parkingspot_res_parkingspot_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='res',
            field=models.ManyToManyField(to='api.reservation'),
        ),
    ]
