# Generated by Django 4.1.3 on 2022-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_parkingspot_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='res',
            field=models.ManyToManyField(blank=True, null=True, to='api.reservation'),
        ),
    ]
