# Generated by Django 4.1.3 on 2022-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_parkingspot_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='res',
            field=models.ManyToManyField(blank=True, to='api.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(),
        ),
    ]
