# Generated by Django 4.1.3 on 2022-11-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_parkingspot_res_alter_reservation_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='res',
            new_name='reservations',
        ),
    ]
