# Generated by Django 4.1.3 on 2022-11-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_res_parkingspot_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parkingSpot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspot'),
        ),
    ]
